/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Containers;

import java.awt.event.WindowEvent;
import javax.swing.*;

public class MainMenuPanel extends javax.swing.JPanel {
    
    public MainMenuPanel() {
        initComponents();
    }
    
    public JButton getBtnPlaygame() {
        return btnPlayGame;
    }
    
    public JButton getBtnHowToPlay() {
        return btnHowToPlay;
    }
    
    public JButton getBtnExitGame() {
        return btnExitGame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPlayGame = new javax.swing.JButton();
        btnHowToPlay = new javax.swing.JButton();
        btnExitGame = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Necro-Caster");

        btnPlayGame.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnPlayGame.setForeground(new java.awt.Color(153, 51, 0));
        btnPlayGame.setText("Play Game");

        btnHowToPlay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnHowToPlay.setForeground(new java.awt.Color(153, 0, 0));
        btnHowToPlay.setText("How To Play");
        btnHowToPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHowToPlayActionPerformed(evt);
            }
        });

        btnExitGame.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnExitGame.setForeground(new java.awt.Color(153, 0, 0));
        btnExitGame.setText("Exit Game");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnExitGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPlayGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHowToPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(135, 135, 135))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPlayGame)
                .addGap(18, 18, 18)
                .addComponent(btnHowToPlay)
                .addGap(18, 18, 18)
                .addComponent(btnExitGame)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHowToPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHowToPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHowToPlayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExitGame;
    private javax.swing.JButton btnHowToPlay;
    private javax.swing.JButton btnPlayGame;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
