/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Containers;

import java.awt.*;
import javax.swing.*;

public class StatsPanel extends javax.swing.JPanel {
    InventoryFrame invFrame;

    
    
    public StatsPanel() {
        setVisible(false);
        initComponents();
    }
    
    public JButton getBtnInv() {
        return inventoryButton;
    }

    public JLabel getAgilityValue() {
        return agilityValue;
    }

    public JLabel getAttackValue() {
        return attackValue;
    }

    public JLabel getDefenseValue() {
        return defenseValue;
    }

    public JLabel getEquippedRing() {
        return equippedRing;
    }

    public JLabel getEquippedRobe() {
        return equippedRobe;
    }

    public JLabel getEquippedStaff() {
        return equippedStaff;
    }

    public JLabel getLevelValue() {
        return levelValue;
    }

    public JProgressBar getHealthProgressBar() {
        return healthProgressBar;
    }

    public JProgressBar getManaProgressBar() {
        return manaProgressBar;
    }

    public JProgressBar getXpProgressBar() {
        return xpProgressBar;
    }
    
    
    
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        statsHeader = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        healthLabel = new javax.swing.JLabel();
        manaLabel = new javax.swing.JLabel();
        attackLabel = new javax.swing.JLabel();
        defenseLabel = new javax.swing.JLabel();
        agilityLabel = new javax.swing.JLabel();
        xpLabel = new javax.swing.JLabel();
        xpProgressBar = new javax.swing.JProgressBar();
        healthProgressBar = new javax.swing.JProgressBar();
        manaProgressBar = new javax.swing.JProgressBar();
        levelValue = new javax.swing.JLabel();
        attackValue = new javax.swing.JLabel();
        defenseValue = new javax.swing.JLabel();
        agilityValue = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        equippedStaff = new javax.swing.JLabel();
        equippedRobe = new javax.swing.JLabel();
        equippedRing = new javax.swing.JLabel();
        inventoryButton = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setBackground(new java.awt.Color(204, 153, 0));
        setToolTipText("");

        statsHeader.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        statsHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statsHeader.setText("Stats");

        levelLabel.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        levelLabel.setText("Level:");

        healthLabel.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        healthLabel.setText("Health:");

        manaLabel.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        manaLabel.setText("Mana:");

        attackLabel.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        attackLabel.setText("Attack:");

        defenseLabel.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        defenseLabel.setText("Defense:");

        agilityLabel.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        agilityLabel.setText("Agility:");

        xpLabel.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        xpLabel.setText("  XP:");

        levelValue.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        levelValue.setText("null");
        levelValue.setToolTipText("");

        attackValue.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        attackValue.setText("null");

        defenseValue.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        defenseValue.setText("null");

        agilityValue.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        agilityValue.setText("null");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        jLabel5.setText("Equipment");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jLabel6.setText("Staff:");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jLabel7.setText("Robe:");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jLabel8.setText("Ring:");

        equippedStaff.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        equippedStaff.setText("null");

        equippedRobe.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        equippedRobe.setText("null");

        equippedRing.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        equippedRing.setText("null");

        inventoryButton.setText("Open Inventory");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(healthLabel)
                                    .addComponent(xpLabel)
                                    .addComponent(levelLabel))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(levelValue))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(xpProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                            .addComponent(healthProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(manaLabel)
                                    .addComponent(attackLabel))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(manaProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(attackValue, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(defenseLabel)
                                    .addComponent(agilityLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agilityValue)
                                    .addComponent(defenseValue)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(statsHeader))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(equippedStaff))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(equippedRobe)
                            .addComponent(equippedRing)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(inventoryButton)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statsHeader)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(levelLabel)
                                    .addComponent(levelValue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xpLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(healthLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(xpProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(healthProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(manaLabel))
                    .addComponent(manaProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attackLabel)
                    .addComponent(attackValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defenseLabel)
                    .addComponent(defenseValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agilityLabel)
                    .addComponent(agilityValue))
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(equippedStaff))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(equippedRobe))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(equippedRing))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inventoryButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agilityLabel;
    private javax.swing.JLabel agilityValue;
    private javax.swing.JLabel attackLabel;
    private javax.swing.JLabel attackValue;
    private javax.swing.JLabel defenseLabel;
    private javax.swing.JLabel defenseValue;
    private javax.swing.JLabel equippedRing;
    private javax.swing.JLabel equippedRobe;
    private javax.swing.JLabel equippedStaff;
    private javax.swing.JLabel healthLabel;
    private javax.swing.JProgressBar healthProgressBar;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel levelValue;
    private javax.swing.JLabel manaLabel;
    private javax.swing.JProgressBar manaProgressBar;
    private javax.swing.JLabel statsHeader;
    private javax.swing.JLabel xpLabel;
    private javax.swing.JProgressBar xpProgressBar;
    // End of variables declaration//GEN-END:variables

}
